<?php

namespace App\Ai;

use App\Enums\AiOutputType;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

final class GeminiAiProvider implements AiProvider
{
    private AiAnonymizer $anonymizer;
    private StubAiProvider $fallbackProvider;

    public function __construct()
    {
        $this->anonymizer = new AiAnonymizer();
        $this->fallbackProvider = new StubAiProvider();
    }

    public function name(): string
    {
        return 'gemini';
    }

    /**
     * @param  array<string, mixed>  $sourceData
     */
    public function generate(AiOutputType $type, array $sourceData): string
    {
        $apiKey = config('ai.gemini.api_key');
        $model = config('ai.gemini.model', 'gemini-1.5-pro');

        if (! $apiKey) {
            Log::warning('Gemini API key is not configured. Falling back to local StubAiProvider.');
            return $this->fallbackProvider->generate($type, $sourceData);
        }

        // Anonymize payload for data privacy
        $anonymizedData = $this->anonymizer->anonymize($sourceData);

        // Compile prompt
        $prompt = $this->compilePrompt($type, $anonymizedData);

        try {
            $response = Http::timeout(10)
                ->post("https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key={$apiKey}", [
                    'contents' => [
                        [
                            'parts' => [
                                ['text' => $prompt]
                            ]
                        ]
                    ],
                    'generationConfig' => [
                        'temperature' => 0.2,
                        'maxOutputTokens' => 2048,
                    ]
                ]);

            if ($response->successful()) {
                $text = $response->json('candidates.0.content.parts.0.text');
                if ($text) {
                    return trim($text) . "\n\nAI-generated by TimeForge (Gemini gateway) from anonymized records.";
                }
            }

            Log::error('Gemini API call failed: ' . $response->body());
        } catch (\Throwable $e) {
            Log::error('Gemini API connection error: ' . $e->getMessage());
        }

        Log::warning('Falling back to local StubAiProvider due to API failure.');
        return $this->fallbackProvider->generate($type, $sourceData);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function compilePrompt(AiOutputType $type, array $data): string
    {
        $typeLabel = match ($type) {
            AiOutputType::DailyWorkSummary => 'Daily Work Summary',
            AiOutputType::WeeklyProductivityReport => 'Weekly Productivity Report',
            AiOutputType::RecurringBlockers => 'Recurring Blockers Report',
            AiOutputType::KpiPerformanceAnalysis => 'KPI Performance Analysis',
            AiOutputType::PayrollValidation => 'Payroll Validation',
            AiOutputType::SupervisorRecommendations => 'Supervisor Recommendations',
            AiOutputType::ProductivityTrendAnalysis => 'Productivity Trend Analysis',
        };

        $jsonData = json_encode($data, JSON_PRETTY_PRINT);

        return <<<PROMPT
You are the TimeForge AI Assistant. Based strictly on the provided JSON source data, generate a {$typeLabel}.

Guidelines:
1. Do not invent any business facts. Every number, name, and statement must be derived from the JSON payload.
2. The user names have been anonymized for data privacy (e.g., mapped to "Employee A", "Employee B"). Use these anonymized names exactly as provided.
3. Keep the output professional, objective, structured, and easy to read.

Anonymized Source Data:
{$jsonData}

Generate the {$typeLabel}:
PROMPT;
    }
}
