<?php

namespace App\Ai;

use App\Enums\AiOutputType;

/**
 * The MVP's only AI provider (per the approved Sprint 11 decisions):
 * fully local, deterministic, template-based rendering of the gathered
 * source data. No network access, no credentials, no inference — every
 * sentence is mechanically derived from stored records, which also makes
 * outputs assertable as exact strings in tests. Swapping in a real
 * provider later is a config/binding change, not an architecture change.
 */
final class StubAiProvider implements AiProvider
{
    private const FOOTER = 'AI-generated by TimeForge (stub provider) from stored records only.';

    public function name(): string
    {
        return 'stub';
    }

    /**
     * @param  array<string, mixed>  $sourceData
     */
    public function generate(AiOutputType $type, array $sourceData): string
    {
        return match ($type) {
            AiOutputType::DailyWorkSummary => $this->dailyWorkSummary($sourceData),
            AiOutputType::WeeklyProductivityReport => $this->weeklyProductivityReport($sourceData),
            AiOutputType::RecurringBlockers => $this->recurringBlockers($sourceData),
        };
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function dailyWorkSummary(array $data): string
    {
        $lines = [
            sprintf('Daily work summary for %s on %s.', $data['user_name'], $data['date']),
            '',
            sprintf(
                '%s logged %s across %s.',
                $data['user_name'],
                $this->minutes($data['total_minutes']),
                $this->pluralize(count($data['entries']), 'time entry', 'time entries'),
            ),
        ];

        foreach ($data['entries'] as $entry) {
            $lines[] = sprintf(
                '- %s (%s, %s) — %s on %s: %s',
                $entry['task'],
                $entry['work_category'] ?? 'uncategorized',
                $entry['task_status'] ?? 'no status',
                $this->minutes($entry['duration_minutes']),
                $this->linkedTarget($entry),
                $entry['description'] ?? 'no description',
            );
        }

        $lines[] = sprintf('Timesheet status for the day: %s.', $data['timesheet_status'] ?? 'no timesheet created');
        $lines[] = $this->dailyScrumLine($data['scrum']);
        $lines[] = $this->dailyKpiLine($data['entries']);
        $lines[] = self::FOOTER;

        return implode("\n", $lines);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function weeklyProductivityReport(array $data): string
    {
        $lines = [
            sprintf('Weekly productivity report for %s, %s to %s.', $data['user_name'], $data['week_start'], $data['week_end']),
            '',
            sprintf(
                'Total logged: %s across %s with time entries.',
                $this->minutes($data['total_logged_minutes']),
                $this->pluralize($data['attendance_days'], 'day', 'days'),
            ),
            sprintf(
                'Approved: %s (%s regular, %s overtime). Pending: %s. Rejected: %s.',
                $this->minutes($data['approved_minutes']),
                $this->minutes($data['regular_minutes']),
                $this->minutes($data['overtime_minutes']),
                $this->minutes($data['pending_minutes']),
                $this->minutes($data['rejected_minutes']),
            ),
            'Daily breakdown:',
        ];

        foreach ($data['daily_breakdown'] as $day) {
            $lines[] = sprintf('- %s: %s', $day['date'], $this->minutes($day['logged_minutes']));
        }

        $lines[] = $this->weeklyTimesheetLine($data['timesheet_status_counts']);
        $lines[] = $data['kpi_progress_entry_count'] === 0
            ? 'No KPI progress was reported this week.'
            : sprintf(
                'KPI progress reported this week: %s across %s.',
                $this->number($data['kpi_progress_total']),
                $this->pluralize($data['kpi_progress_entry_count'], 'entry', 'entries'),
            );
        $lines[] = self::FOOTER;

        return implode("\n", $lines);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    private function recurringBlockers(array $data): string
    {
        $lines = [
            sprintf('Recurring blocker report for %s, %s to %s.', $data['department_name'], $data['period_start'], $data['period_end']),
            '',
            sprintf(
                'Scanned %s in the period; blockers were reported in %d of them.',
                $this->pluralize($data['scanned_entries'], 'daily scrum entry', 'daily scrum entries'),
                $data['entries_with_blockers'],
            ),
        ];

        if ($data['recurring_blockers'] === []) {
            $lines[] = 'No recurring blockers were found in this period.';
        } else {
            $lines[] = 'Recurring blockers (same blocker reported on 2 or more distinct days):';

            foreach ($data['recurring_blockers'] as $blocker) {
                $lines[] = sprintf(
                    '- "%s" — %s (%s) by %s.',
                    $blocker['text'],
                    $this->pluralize($blocker['occurrences'], 'occurrence', 'occurrences'),
                    implode(', ', $blocker['dates']),
                    implode(', ', $blocker['employees']),
                );
            }
        }

        $lines[] = self::FOOTER;

        return implode("\n", $lines);
    }

    /**
     * @param  array<string, mixed>  $scrum
     */
    private function dailyScrumLine(?array $scrum): string
    {
        if ($scrum === null) {
            return 'No daily scrum entry was submitted for this day.';
        }

        return sprintf(
            'Daily scrum — previous: %s | planned: %s | blockers: %s | notes: %s.',
            $scrum['previous_work'],
            $scrum['planned_work'],
            $scrum['blockers'] ?? 'none reported',
            $scrum['notes'] ?? 'none',
        );
    }

    /**
     * @param  array<int, array<string, mixed>>  $entries
     */
    private function dailyKpiLine(array $entries): string
    {
        $parts = [];

        foreach ($entries as $entry) {
            if ($entry['kpi_name'] !== null && $entry['kpi_progress_value'] !== null) {
                $parts[] = sprintf(
                    '%s +%s%s',
                    $entry['kpi_name'],
                    $this->number($entry['kpi_progress_value']),
                    $entry['kpi_unit'] !== null ? ' '.$entry['kpi_unit'] : '',
                );
            }
        }

        return $parts === []
            ? 'No KPI progress was reported on this day.'
            : 'KPI progress reported: '.implode('; ', $parts).'.';
    }

    /**
     * @param  array<string, int>  $counts  keyed by timesheet status value
     */
    private function weeklyTimesheetLine(array $counts): string
    {
        $parts = [];

        // Fixed order keeps the sentence deterministic regardless of the
        // order timesheets were created in.
        foreach (['approved', 'submitted', 'revision_requested', 'rejected'] as $status) {
            if (($counts[$status] ?? 0) > 0) {
                $parts[] = $counts[$status].' '.$status;
            }
        }

        return $parts === []
            ? 'No timesheets exist for this week.'
            : 'Timesheets: '.implode(', ', $parts).'.';
    }

    /**
     * @param  array<string, mixed>  $entry
     */
    private function linkedTarget(array $entry): string
    {
        if ($entry['project'] !== null && $entry['client'] !== null) {
            return $entry['project'].' for '.$entry['client'];
        }

        return $entry['project'] ?? $entry['client'] ?? 'no linked project or client';
    }

    private function minutes(int $minutes): string
    {
        return sprintf('%dh %02dm', intdiv($minutes, 60), $minutes % 60);
    }

    private function number(float|int $value): string
    {
        return rtrim(rtrim(number_format((float) $value, 2, '.', ''), '0'), '.');
    }

    private function pluralize(int $count, string $singular, string $plural): string
    {
        return $count.' '.($count === 1 ? $singular : $plural);
    }
}
